all:
	ca65 ex01.asm -o ex01.o
	ld65 ex01.o   -o ex01.nes -C nes.cfg

	ca65 ex02.asm -o ex02.o
	ld65 ex02.o   -o ex02.nes -C nes.cfg

	ca65 ex03.asm -o ex03.o
	ld65 ex03.o   -o ex03.nes -C nes.cfg

	ca65 ex04.asm -o ex04.o
	ld65 ex04.o   -o ex04.nes -C nes.cfg

	ca65 ex05.asm -o ex05.o
	ld65 ex05.o   -o ex05.nes -C nes.cfg

	ca65 ex06.asm -o ex06.o
	ld65 ex06.o   -o ex06.nes -C nes.cfg

	ca65 ex07.asm -o ex07.o
	ld65 ex07.o   -o ex07.nes -C nes.cfg

	ca65 ex08.asm -o ex08.o
	ld65 ex08.o   -o ex08.nes -C nes.cfg

	ca65 ex09.asm -o ex09.o
	ld65 ex09.o   -o ex09.nes -C nes.cfg

clean:
	rm *.o *.nes
